site_name: Questivity LTI
site_url: https://cs-3337-group-8.github.io/Questivity/

theme:
    name: cinder

repo_url: https://github.com/CS-3337-Group-8/Questivity"

extra:
    include_search: false

nav:
    - QuestivityDB: db-api.md
    - NGINX: nginx.md
    - Docker: docker.md

plugins:
    - mermaid2:
          version: "9.4.3"
          arguments:
              theme: "dark"
              themeVariables:
                  primaryColor: "#BB2528"
                  primaryTextColor: "#fff"
                  primaryBorderColor: "#7C0000"
                  lineColor: "#F8B229"
                  secondaryColor: "#006100"
                  tertiaryColor: "#fff"
    - panzoom:
          mermaid: true
          images: false

copyright: |
    &copy; 2024 <a href="https://github.com/CS-3337-Group-8" target="_blank" rel="noopener">CS-3337-Group-8</a>
