networks:
    database:
        driver: bridge
    proxy:
        driver: bridge
    canvas:
        driver: bridge

services:
    web:
        container_name: web
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./web/html:/usr/share/nginx/html
            - ./web/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - heimdall
            - db-api
            - gd-export
            - adminer
        networks:
            - database
            - proxy
            - canvas

    db:
        container_name: db
        image: mysql
        restart: unless-stopped
        expose:
            - "3306"
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
            TZ: "America/Los_Angeles"
        networks:
            - database
        depends_on:
            - dozzle

    db-api:
        container_name: db-api
        build: ./db-api
        restart: unless-stopped
        expose:
            - "3000"
        environment:
            DB_HOST: db
            DB_USER: user
            DB_PASSWORD: password
            DB_NAME: database
            TZ: "America/Los_Angeles"
            PORT: "3000"
            API_KEY: 9a1442ec-0d0a-4b76-9b1a-38a526d51f2a
        depends_on:
            - db
        networks:
            - database

    canvas:
        container_name: canvas
        image: lbjay/canvas-docker
        restart: unless-stopped
        expose:
            - "3000"
        networks:
            - canvas

    gd-export:
        container_name: gd-export
        build:
            context: .
            dockerfile: ./gd-export/Dockerfile
            args:
                GODOT_VERSION: 3.6-stable
                GODOT_VERSION_DIR: 3.6.stable
                EXPORT_NAME: HTML5
                OUTPUT_FILENAME: index.html
        restart: no
        volumes:
            - ../godot:/build/src
            - ./web/html/questivity:/build/output

    dozzle:
        container_name: dozzle
        restart: unless-stopped
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "8080"
        networks:
            - proxy

    adminer:
        container_name: adminer
        restart: unless-stopped
        image: adminer
        expose:
            - "8080"
        networks:
            - database

    heimdall:
        container_name: heimdall
        image: linuxserver/heimdall
        restart: unless-stopped
        environment:
            PUID: 1000
            PGID: 1000
        volumes:
            - ./heimdall/app.sqlite:/config/www/app.sqlite
            - ./heimdall/backgrounds:/config/www/backgrounds
            - ./heimdall/icons:/config/www/icons

        expose:
            - "80"
        networks:
            - proxy
