volumes:
    database:

services:
    web:
        image: "httpd:latest"
        ports:
            - "80:80"
        volumes:
            - "../html:/usr/local/apache2/htdocs"
        depends_on:
            - "api"
            - "godot-export"

    db:
        image: "mysql"
        container_name: "db"
        restart: "always"
        ports:
            - "5000:3306"
        volumes:
            - "database:/var/lib/mysql"
            - "./db:/docker-entrypoint-initdb.d" # Mount the init script directory
        environment:
            - "MYSQL_DATABASE=database"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=password"
            - "MYSQL_ROOT_PASSWORD=rootpassword"

    canvas:
        image: "lbjay/canvas-docker"
        container_name: "canvas"
        restart: "always"
        ports:
            - "3000:3000"

    api:
        build: ./api # Pointing to the directory where the Node.js app is located
        restart: "always"
        ports:
            - "4000:3000"
        environment:
            - "DB_HOST=db"
            - "DB_USER=user"
            - "DB_PASSWORD=password"
            - "DB_NAME=database"
        depends_on:
            - "db"

    godot-export:
        build:
            context: .
            dockerfile: "./godot-export/Dockerfile"
            args:
                - "GODOT_VERSION=3.6-stable"
                - "GODOT_VERSION_DIR=3.6.stable"
                - "EXPORT_NAME=HTML5"
                - "OUTPUT_FILENAME=index.html"
        volumes:
            - "../godot:/build/src"
            - "./web/html:/build/output"
