name: Deploy MkDocs Site

on:
    push:
        branches:
            - master
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository files
            - uses: actions/checkout@v3

            # Set up Python
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.x

            # Install dependencies, including the Mermaid plugin
            - run: |
                  pip install mkdocs-material
                  pip install mkdocs-cinder
                  pip install pillow cairosvg
                  pip install mkdocs-mermaid2-plugin

            # Deploy to GitHub Pages
            - run: mkdocs gh-deploy --force
